### ISSUE TITLE
My player worked once but doesn't run anymore??

### ISSUE THREAD

**Issue by Nils55** [ripose-jp/Memento#192] opened 2024-01-06 22:52 UTC
I installed Memento on my windows 10, ran a video on it once, even restarted multiple times to tweak configs, it ran fine. Then a few hours later I tried to open the app again and it just doesn't launch. Tried reinstalling in different places, wiping everything, wiping the local appdata, tried launching from the zip version, running as admin, restarting the pc, the app is just permanently cursed now.

**Comment by ripose-jp** [comment] 2024-01-06 23:08
Try this https://github.com/ripose-jp/Memento/issues/172#issuecomment-1657296087
Do me a favor though. Before deleting `memento`, right click and click export the registry keys. If this fixes your issue, I'd like you to either post or email me the registry entries you exported. It will help me figure out what setting is causing the problem.

**Comment by Nils55** [comment] 2024-01-06 23:16
[Documents.zip](https://github.com/ripose-jp/Memento/files/13851649/Documents.zip)

Thank you very much, that worked! I hope I got the correct files, let me know if there's a mistake.

**Comment by ripose-jp** [comment] 2024-01-06 23:23
Thanks. Files look good to me. I'll see if I can reproduce this. I'm going to close this as a duplicate of #172 though.

**Closed** 2024-01-06 23:23 UTC
Labels: bug, duplicate

**Comment by ripose-jp** [comment] 2024-01-07 01:27
The crash is caused by setting **Behavior** → **Hide cursor with OSC** to unchecked and restarting Memento. Make sure to keep this option checked for the time being. I'll try to get a release out to fix this in the next couple days.
