### ISSUE TITLE
Memento cannot tell if a word is in your deck if added externally

### ISSUE THREAD

**Issue by 0xspringtime** [ripose-jp/Memento#146] opened 2023-02-08 20:36 UTC
When selecting a word, Memento still offers the "Add Anki note" option if the word exists in the deck but was not added by Memento, making it hard to tell whether you've already made a note based on the word.

**Comment by 0xspringtime** [comment] 2023-02-08 20:48
Attempted fixes:
Change Duplicate Policy - was always set to "None"
Give all words memento tag - no effect
Normalize first field - all cards use "expression"

**Comment by ripose-jp** [comment] 2023-02-09 01:39
I can't reproduce this issue adding 昨日 using Yomichan. Make a deck with two cards that should conflict, one from Memento and one not, and upload it somewhere. Make sure you give me your Memento card template as well.

I will let you know that I've seen of ton of issues like this and so far all of them have been user error.

**Comment by 0xspringtime** [comment] 2023-02-10 02:10
Here is a deck where I replicated the issue using my yomichan model then with memento and here is my memento card template
https://anonfiles.com/62c1b7X1ye/test_apkg
![Screenshot from 2023-02-09 21-04-56](https://user-images.githubusercontent.com/110655352/217982211-193cd62b-f3e0-4942-9ed8-bb8356fb62d1.png)
![Screenshot from 2023-02-09 21-04-40](https://user-images.githubusercontent.com/110655352/217982220-dd5c81f0-2537-4a42-898e-01d3624c4a2d.png)

**Comment by ripose-jp** [comment] 2023-02-10 06:17
In the deck you sent, you have two different models. One for Memento and one for Yomichan. Anki isn't built to detect duplicate cards if they use different models. Read this post for more info
https://forums.ankiweb.net/t/anki-appears-to-no-longer-detect-duplicates-upon-new-card-entry/2005/4

Closing this because it's not a Memento problem.

**Closed by ripose-jp** 2023-02-10 06:17 UTC
Labels: invalid
