### ISSUE TITLE
HiDPI resolution issue

### ISSUE THREAD

**Issue by aemino** [ripose-jp/Memento#98] opened 2022-04-05 02:11 UTC
Hello there. I'm testing out Memento on Wayland (`QT_QPA_PLATFORM=wayland`), using Sway in particular. For some reason, when I apply the option `vo=gpu` in `mpv.conf`, a secondary window is created, and this window is where the video is rendered. Everything else (UI, subtitles, etc.) remains in the main window.

Without applying this option, the video is rendered in the main window, but at an excessively large resolution when the window is on my secondary monitor. As far as I can tell, neither of these issues are present with stock mpv.

sway: v1.7
memento: v0.5.5-1
qt: v5.15.3

Please let me know if there is any additional information that I can provide. I would be happy to test patches, and if the fix isn't too involved, I might be able to submit a patch with a pointer in the right direction.

**Comment by ripose-jp** [comment] 2022-04-05 03:38
>For some reason, when I apply the option `vo=gpu` in `mpv.conf`, a secondary window is created, and this window is where the video is rendered.

While you can change to `vo` in Memento, if you use anything other than `vo=libmpv` this is just what is going to happen. Nothing I can really do about it. From my understanding, `vo=lipmpv` and `vo=gpu` are roughly equivalent in what they'll support, at least according to [this](https://github.com/mpv-player/mpv/blob/master/DOCS/man/vo.rst). 

>Without applying this option, the video is rendered in the main window, but at an excessively large resolution when the window is on my secondary monitor. As far as I can tell, neither of these issues are present with stock mpv.

I haven't done any testing on Wayland (I use NVidia cards) and don't have two monitors, so this is going to be a difficult one for me to debug. I can try to install some Wayland distro on my old laptop and run it off the integrated graphics to see if I can reproduce this bug. That's going to be a bit of a project and I'm a little busy right now, so I can't promise any results any time soon.

If I just had to guess what the issue is given what I know, I'd assume it's something to do with drivers. Can you tell me what graphics card and driver you're using?

**Comment by aemino** [comment] 2022-04-05 04:23
I'm testing on my laptop, so my graphics card is integrated; it's an Intel Iris Xe. Therefore the driver should be `i915` if I'm not mistaken.

**Comment by ripose-jp** [comment] 2022-04-05 04:25
I have the hardware to reproduce the bug then. I'll let you know if I need any more information.

**Comment by ripose-jp** [comment] 2022-04-05 19:24
I remembered that I had problems with mpv scaling on HiDPI displays about a year ago that had similar symptoms to the bug you described. Then it hit me that the DPI between your laptop and external display are probably different and Memento isn't updating the DPI properly when you move the window between screens. I still don't have any way to test whether or not this works, but here's a patch that I think might fix your issue.

[patch.txt](https://github.com/ripose-jp/Memento/files/8421261/patch.txt)

If you don't know how to apply patches, just navigate to the Memento git directory and type `git apply /path/to/patch.txt`.

Let me know if this solves the problem.

**Comment by ripose-jp** [comment] 2022-04-05 19:39
I was able to reproduce this bug on macOS and this patch fixed it.

**Comment by aemino** [comment] 2022-04-05 20:08
Your inference was exactly right! I probably should have mentioned it from the outset, but my laptop has a HiDPI display (2256x1504) while my external monitor is QHD (2560x1440). I tried out the patch and it appears to resolve the issue. Many thanks, both for your work on this project as well as the quick fix.

**Comment by ripose-jp** [comment] 2022-04-05 20:21
Thanks for the issue and the feedback, the patch has been merged into master.

**Closed by ripose-jp** 2022-04-05 20:21 UTC
Labels: bug
