### ISSUE TITLE
Allow scanning popup items

### ISSUE THREAD

**Issue by kik4444** [ripose-jp/Memento#239] opened 2024-09-06 13:12 UTC
Lately I've been trying to use a monolingual Japanese dictionary and realized that Yomitan(chan) has one feature to make this considerably easier. You can hover over words in the popup and get a second child popup for the selected word. Then you can select another word in there and get a 3rd child popup and so on.

This is all written here in the screenshot with the `Popup` settings. https://learnjapanese.moe/monolingual/#yomichan-the-better-way-to-go-monolingual

Can this feature be added to Memento?

**Comment by ripose-jp** [comment] 2024-09-06 17:35
Duplicate of #80.

This has been a feature for years. Just use whatever you have your modifier key set to to scan words. By default it's shift.

**Closed by ripose-jp** 2024-09-06 17:35 UTC
Labels: duplicate

**Comment by kik4444** [comment] 2024-09-06 22:04
Oh I see. Sorry for the duplicate. I keep the scan set to `Hover` so I don't hold down any modifier keys and assumed it would work just by hovering over the popup like it does in Yomitan.
