### ISSUE TITLE
Anki Card Generation Not Working

### ISSUE THREAD

**Issue by GitStewie** [ripose-jp/Memento#138] opened 2022-12-14 06:33 UTC
Is there anything obviously wrong here?

![image](https://user-images.githubusercontent.com/48700222/207521483-d743628e-0843-4e83-8254-5a358fbf4c6d.png)
![image](https://user-images.githubusercontent.com/48700222/207521600-3b7ef481-961a-40fa-b0dc-1dd2ac66431e.png)
![image](https://user-images.githubusercontent.com/48700222/207521637-5fd597c1-fe65-44c0-9409-3b9f50f493e1.png)
![image](https://user-images.githubusercontent.com/48700222/207522668-1e7e15d8-684b-43ae-a24f-d7a1cf612df5.png)
![image](https://user-images.githubusercontent.com/48700222/207522704-237b8742-755d-4804-be13-31c5a32090ce.png)

If it helps, I also sometimes have to click a button a lot of times before it works.  Such as apply in the Search options page.  Furthermore, when I click connect in Anki integration, it selects my "Card Tags" area.  However, I do have AnkiConnect installed, and can do the whole search in Anki configuration when hovering over words.

**Comment by ripose-jp** [comment] 2022-12-15 01:39
I need more information regarding what "not working" is.

Is the **+** button not visible when you search words? If it is visible, what happens when you press it? If it isn't visible, is there a button with [three horizontal lines](https://en.wikipedia.org/wiki/Hamburger_button#/media/File:Hamburger_icon.svg) present?

>If it helps, I also sometimes have to click a button a lot of times before it works.

I can't reproduce this and no one has ever reported something similar to this before.

>Such as apply in the Search options page.

To apply search options? I can't reproduce this.

>Furthermore, when I click connect in Anki integration, it selects my "Card Tags" area. 

It does this because the connect button is disabled for a moment while it is in the process of connecting to Anki. When a widget with focus is disabled, Qt automatically focuses on the next focusable widget, in this case the Card Tags line edit. It's not a bug, just a quirk.

>However, I do have AnkiConnect installed, and can do the whole search in Anki configuration when hovering over words.

Are you talking about the auto complete that show up when you start typing tags in Anki Integration Settings? Or are you talking about searching for words in subtitles? Either way, neither rely on AnkiConnect working.

**Comment by GitStewie** [comment] 2022-12-15 03:40
Yeah, the three horizontal line button is present.  The + button is not visible when I search words.

**Comment by ripose-jp** [comment] 2022-12-15 04:18
Then you messed up your card template somehow. Since there's a field for every Memento tag in your card model, I assume that you've made a custom model. I've never made a custom card model before, so I can't tell you what you've done wrong. Whatever it is though, AnkiConnect doesn't like it.

This doesn't look like a problem with Memento, so I'm closing it.

**Closed by ripose-jp** 2022-12-15 04:18 UTC
Labels: invalid
