### ISSUE TITLE
scripts don't work

### ISSUE THREAD

**Issue by OltiP2** [ripose-jp/Memento#59] opened 2022-01-09 22:09 UTC
I've tried importing scripts like mpvacious on the \AppData\Local\memento\ folder but it's not working i also tried creating a "scripts" folder and importing the script there but it still doesn't work im on Windows 10 i've also tried a script called clipshot which copies your screenshots to your clipboard but that also didn't work

**Comment by Calvin-Xu** [comment] 2022-01-09 22:22
I use clipshot and I can confirm it works on macOS 12.1. Someone has tried using mpvacious with Memento on Windows and reports that it works: https://github.com/ripose-jp/Memento/issues/10.

I don't use Windows so can't provide more info.

**Comment by ripose-jp** [comment] 2022-01-09 22:25
I can confirm clipshot is working on Windows 10.

Make sure all your scripts are in the `scripts` and restart Memento whenever you want to load a new script.

**Comment by OltiP2** [comment] 2022-01-09 22:36
I remade the scripts folder and put clipshot in it and its working i might've misspelled scripts but mpvacious it's still not working maybe because its a script with in a folder like this
![image](https://user-images.githubusercontent.com/97410429/148703916-38d0f7fc-8d16-4b06-999f-a21b47acb45f.png)

**Comment by ripose-jp** [comment] 2022-01-09 22:39
mpv doesn't load scripts in subfolders. If you want to load a script, it will have to end in `.lua` or `.js`. Just move the contents of that folder to `scripts` and everything will probably work.

**Comment by OltiP2** [comment] 2022-01-09 22:44
I imported the all the scipts on the scripts folder but it's still doesn't work

**Comment by ripose-jp** [comment] 2022-01-09 22:47
Post a screenshot of your scripts folder.

**Comment by OltiP2** [comment] 2022-01-09 22:50
This is the mpvacious folder 
![image](https://user-images.githubusercontent.com/97410429/148704368-acea48cb-1135-4776-8a52-c4104fa50a8b.png)
This is my scipts folder 
![image](https://user-images.githubusercontent.com/97410429/148704392-4ec541b9-7dad-434f-bd1c-c81ffef7802d.png)

**Comment by ripose-jp** [comment] 2022-01-09 23:00
I'm not sure what the issue is. I know other people have had success with getting mpvacious to work, so I don't think it's a problem with Memento. You might want to try mpvacious's issue tracker since this seems like it has more to do with their script than Memento.

**Comment by OltiP2** [comment] 2022-01-09 23:03
I don't know but in mpv it works fine even when its in the folder

**Comment by ripose-jp** [comment] 2022-01-09 23:26
I seems I was wrong about the folder thing, but I just tested it using the instructions in mpvacious's README and everything worked fine.

**Comment by OltiP2** [comment] 2022-01-09 23:41
i redownloaded the zip and extracted it works now but it shows me this
![image](https://user-images.githubusercontent.com/97410429/148705959-3e1cfc87-95ad-4c04-8002-d11de7832942.png)

**Comment by ripose-jp** [comment] 2022-01-09 23:52
Not sure. The version of mpv bundled with Memento on Windows definitely supports webp and opus, so that's potentially a bug in mpvacious.

**Comment by OltiP2** [comment] 2022-01-09 23:54
yeah its pretty weird since it works on normal mpv

**Comment by ripose-jp** [comment] 2022-01-10 00:01
You could try using an older version of mpvacious and seeing if anything changes.

Other than that, do mind if I close this?

**Comment by OltiP2** [comment] 2022-01-10 00:02
No i don't thank you for the help

**Comment by ripose-jp** [comment] 2022-01-10 00:09
What are you trying to accomplish then? I can't fix the issue if it's something on mpvacious' end.

Memento and mpvacious are more or less functionally equivalent if you're trying to make Anki cards.

**Comment by OltiP2** [comment] 2022-01-10 00:12
no i meant to say no i dont mind than i said thank thank you for your help i dont responded to the do you mind if i close this

**Comment by ripose-jp** [comment] 2022-01-10 00:13
lol, don't forget your commas next time

**Closed by ripose-jp** 2022-01-10 00:13 UTC
Labels: question
