### ISSUE TITLE
UI: options for OSC visibility

### ISSUE THREAD

**Issue by K1nlaS** [ripose-jp/Memento#105] opened 2022-04-30 16:31 UTC
Correct me if I am wrong, but as far as I can see the Memento's OSC works separately of mpv's. I think that adding OSC visibility toggle and some of the options that mpv has such as minmousemove, deadzonesize, hidetimeout, fadeduration would significantly increase ease of use.

For example, I do not like when the OSC bar comes up every single time when I move the mouse.  This is where minmousemove and deadzonesize are a great help since I can set them up in such a way so that the OSC bar wouldnt appear unless the mouse enters its space. Having it come up while you are hovering over the unknown words is really distracting.

**Comment by ripose-jp** [comment] 2022-04-30 18:04
Part of what you're asking for is a duplicate of #95. I'll see what I can do for the rest of it.

**Comment by ripose-jp** [comment] 2022-05-08 21:21
I've implemented a user-settable minimum mouse movement, hide timeout, and fade duration for the OSC.

I have decided against implementing a deadzone because it doesn't make as much sense in Memento as it does in mpv. In mpv, the default OSC only exists at the bottom of the screen, while in Memento both the menu bar and bottom bar are visible upon moving the mouse. If a deadzone was implemented, it could really only exist in the middle of the screen since crucial functionality exists at both the top and bottom of the the screen. I simply don't like the idea of only showing the menu bar or only showing the bottom bar based on what area the cursor is in.

When I merge these changes into master, I'll close this issue.

**Closed** 2022-05-08 22:51 UTC
Labels: enhancement
