### ISSUE TITLE
Video does not play

### ISSUE THREAD

**Issue by ZekkieMcCormick** [ripose-jp/Memento#219] opened 2024-05-06 03:30 UTC
Running on Arch Linux, never had an issue before. Last successfully ran a few weeks ago, but now any video that opens (which previously would) does not work. I've tried launching a video from both outside and inside Memento, but it leaves a blank screen with no time information.

**Comment by ripose-jp** [comment] 2024-05-06 03:40
mpv v0.38.0 made a breaking change with how videos were loaded in Memento. This was fixed in Memento v1.3.0 which was released specifically to fix this for AUR users. Try updating Memento and let me know if that fixes it.

**Comment by ZekkieMcCormick** [comment] 2024-05-13 12:54
I double checked I was on 1.3 and that mpv was updated, it does not play in memento but in mpv

**Comment by ripose-jp** [comment] 2024-05-15 03:03
I can't reproduce this on Manjaro, KDE Neon, or Gentoo with Memento v1.3.0 and mpv v0.38.0. Try launching Memento from the command line and then opening a file. What does the console show?

**Comment by ripose-jp** [comment] 2024-06-09 03:18
Closing this due to inactivity.

**Closed by ripose-jp** 2024-06-09 03:18 UTC
Labels: linux
