### ISSUE TITLE
Can't open on MAC M3 Arm 

### ISSUE THREAD

**Issue by childishweb** [ripose-jp/Memento#205] opened 2024-03-14 10:23 UTC
“Memento 3.app” is damaged and can’t be opened. You should move it to the Bin.

Version 1.2.1 Works. Latest has issues.

**Comment by jlangeblom** [comment] 2024-03-14 12:01
Is there also a method to take screenshots without subtitles?

**Comment by ripose-jp** [comment] 2024-03-15 03:28
I can't reproduce this even if I run it on a system without Homebrew. What version of macOS are you running?

**Comment by jlangeblom** [comment] 2024-03-15 09:29
Hi, 

M3 Max

Mac OS: 14.3.1

Cheers

**Comment by Toyking10** [comment] 2024-04-08 02:17
Same issue on M1 Ultra.

Mac Studio

MacOS: 14.3.1

**Comment by Calvin-Xu** [comment] 2024-04-08 05:35
I can confirm building from current master on M3 does not have issues.

**Comment by ripose-jp** [comment] 2024-04-12 03:07
I can't reproduce it, so it seems like I'll have to do a fresh install to try and reproduce the issue.

**Comment by ripose-jp** [comment] 2024-06-24 00:20
This should be fixed with v1.4.0. I've spun up a macOS 14.5 VM without Hombrew installed and was able to verify that they work there. If you continue to have issues, feel free to reopen this.

**Closed by ripose-jp** 2024-06-24 00:20 UTC
Labels: bug, macos, distribution

**Comment by wastu01** [comment] 2025-08-03 17:57
I am using Mac M4 with these env, in my case it can work
- **Device**: Mac M4
- **OS**: macOS 15.5
- **Memento**: v1.6.0
- **Anki**: ⁨25.02.5
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
