### ISSUE TITLE
Cannot create card from sentences with <> between them

### ISSUE THREAD

**Issue by OltiP2** [ripose-jp/Memento#142] opened 2023-01-12 09:21 UTC
![memento](https://user-images.githubusercontent.com/97410429/212026819-d050011b-5050-4cc5-94a0-022ad909191c.png)
there is no + sign to add
this is for all the sentences that are surrounded by <>

**Comment by ripose-jp** [comment] 2023-01-13 01:21
I can't reproduce the issue.

![image](https://user-images.githubusercontent.com/72582120/212214511-17ab3607-711a-46c9-a6f3-a7454a7e3cc1.png)

It's likely a problem with your card template or there already being a card that uses 目指す in a way that would make AnkiConnect think this one is a duplicate. Clicking the hamburger button may shed some light on what is confusing AnkiConnect.

**Comment by OltiP2** [comment] 2023-01-13 03:35
I tried to close and open all the apps but i still couldn't fix it, The next day when I tried this again it does work so I don't know what was causing it to think that it was a duplicate that day.

**Comment by ripose-jp** [comment] 2023-01-13 05:51
A lot of things could cause this. Since there's no way to reproduce this and those angle braces have no special significance in Memento's code base, I'm going to close this. If you find a way to reliability reproduce this, feel free to reopen the issue.

**Closed by ripose-jp** 2023-01-13 05:51 UTC
